export type Lang = "en" | "hi" | "mr";
export const LANGS: { code: Lang; label: string }[] = [
  { code: "en", label: "EN" },
  { code: "hi", label: "हिंदी" },
  { code: "mr", label: "मराठी" },
];

const en = {
  home: "Home",
  nav_pulley: "Pulley Systems",
  nav_wall: "Wall Mount & Stands",
  nav_gallery: "Gallery",
  nav_reviews: "Reviews",
  nav_retailer: "Become a Retailer",
  nav_contact: "Contact",
  nav_open: "Open Terrace System",
  nav_ceiling: "Ceiling Mount System",
  nav_all: "All Drying Systems",
  nav_fold: "Foldable Wall Stand",
  search_ph: "Find a product...",
  account: "Account",
  cart: "Cart",
  call_now: "Call Now",
  hero_eb: "India's trusted drying solutions",
  hero_l1: "Dry smart.",
  hero_l2: "Save space.",
  hero_sub:
    "Pulley-operated terrace and ceiling systems and foldable wall stands: 304-grade steel, installed across Pune in days. 1,00,000+ happy homes.",
  hero_cta: "View the collection",
  b1t: "304-Grade", b1s: "Stainless Steel",
  b2t: "Space Saving", b2s: "Design",
  b3t: "Free Installation", b3s: "in Pune",
  b4t: "1 Year", b4s: "Warranty",
  cat_open: "Open Terrace", cat_open_s: "Pulley Systems for Open Spaces",
  cat_ceil: "Ceiling Mount", cat_ceil_s: "Space-Saving Ceiling Systems",
  cat_wall: "Wall Mount", cat_wall_s: "Strong and Foldable Wall Stands",
  cat_all: "All Systems", cat_all_s: "Explore Complete Range",
  pop_eb: "Our popular products",
  best: "Bestsellers.",
  ed_t: "Not just a stand, a smarter way to dry for every home",
  ed_s: "We are not just a store. We are Pune's own dry-system maker, helping 1,00,000+ homes reclaim their balconies with 304-grade steel systems built to last for years.",
  clients_t: "Corporate Clients.",
  view_all: "View all products",
  insp_t: "Get inspired.",
  insp1: "How do you choose the right drying system?",
  insp2: "How do you free up your balcony?",
  insp3: "Drying tools you cannot live without",
  get_insp: "Get inspired",
  moment_l1: "Take your",
  moment_l2: "moment.",
  rated_t: "Rated 4.8/5.",
  cta_t: "Free site visit across Pune.",
  cta_quote: "Get a free quote",
  cta_cart: "View cart",
  foot_tag:
    "Clothes drying systems to love. Designed in Pune, built with 304-grade steel, installed in 1,00,000+ homes since 2014.",
  foot_shop: "Shop",
  foot_service: "Service",
  foot_contact: "Contact",
  foot_about: "About us",
  shop_title: "Drying rack",
  shop_desc:
    "Clothes horses to fall in love with. Dry without a dryer on a pulley-operated Excellent Dry system instead. Stable, easy to use, and available for terrace, ceiling and wall.",
  filter_t: "Filter Results",
  filter_cat: "Categories",
  filter_all: "All systems",
  filter_pulley: "Pulley drying system",
  filter_ceiling: "Ceiling drying rack",
  filter_wall: "Wall mounted dryer",
  filter_size: "Size",
  filter_colour: "Colour",
  products_n: "products",
  sort_by: "Sort By",
  sort_rec: "Recommended",
  sort_low: "Price low",
  sort_high: "Price high",
  d_b1: "Free measurement guidance on call/WhatsApp",
  d_b2: "Professional installation across Pune (60-90 min)",
  d_b3: "GST invoice and service support on call",
  d_order: "Order this product.",
  d_ordernow: "Order Now",
  d_add: "Add to Cart",
  d_added: "Added to cart",
  card_add: "Add to Cart",
  card_added: "Added",
  cart_title: "Your cart.",
  cart_empty_t: "Cart is empty.",
  cart_empty_s: "Add a drying system to get started.",
  cart_browse: "Browse products",
  cart_checkout_t: "Checkout.",
  cart_checkout_s: "Send this cart for a free callback, or order instantly on WhatsApp.",
  cart_subtotal: "Subtotal",
  cart_save: "you save",
  cart_wa: "Order instantly on WhatsApp",
  form_name: "Your name *",
  form_phone: "Phone / WhatsApp *",
  form_area: "Area in Pune (e.g. Baner)",
  form_product: "Product of interest",
  form_msg: "Message (size, floor, balcony...)",
  form_submit: "Request Free Callback",
  form_sending: "Sending...",
  form_orcall: "or call",
  form_thanks: "Thank you",
  form_back: "We will call you back within a few working hours.",
  form_wa: "Confirm instantly on WhatsApp",
  contact_t: "Contact.",
  contact_call: "Call us",
  contact_visit: "Visit",
  contact_cb: "Request callback.",
  about_t: "Pune's own drying-system maker.",
  gallery_t: "Get inspired.",
  gallery_s: "Real fittings across Pune. New photos are added from Admin Media.",
  testi_t: "Rated 4.8/5.",
  ret_t: "Become a retailer.",
  delivery_t: "Delivery areas",
  select_size: "Select size and lines:",
  nav_clients: "Clients",
  cli_t: "Our Valuable Clients.",
  cli_res: "Residential Clients",
  cli_govt: "Government Clients",
  cli_hostels: "Hostels",
};

export type Key = keyof typeof en;

const hi: Record<Key, string> = {
  home: "होम",
  nav_pulley: "पुली सिस्टम",
  nav_wall: "वॉल माउंट और स्टैंड",
  nav_gallery: "गैलरी",
  nav_reviews: "समीक्षाएं",
  nav_retailer: "रिटेलर बनें",
  nav_contact: "संपर्क",
  nav_open: "ओपन टेरेस सिस्टम",
  nav_ceiling: "सीलिंग माउंट सिस्टम",
  nav_all: "सभी ड्राइंग सिस्टम",
  nav_fold: "फोल्डेबल वॉल स्टैंड",
  search_ph: "उत्पाद खोजें...",
  account: "खाता",
  cart: "कार्ट",
  call_now: "अभी कॉल करें",
  hero_eb: "भारत का भरोसेमंद ड्राइंग सॉल्यूशन",
  hero_l1: "स्मार्ट सुखाएं।",
  hero_l2: "जगह बचाएं।",
  hero_sub:
    "पुली वाले टेरेस और सीलिंग सिस्टम और फोल्डेबल वॉल स्टैंड: 304-ग्रेड स्टील, पुणे में कुछ ही दिनों में इंस्टॉलेशन। 1,00,000+ खुश घर।",
  hero_cta: "कलेक्शन देखें",
  b1t: "304-ग्रेड", b1s: "स्टेनलेस स्टील",
  b2t: "जगह बचाने वाला", b2s: "डिज़ाइन",
  b3t: "मुफ्त इंस्टॉलेशन", b3s: "पुणे में",
  b4t: "1 साल", b4s: "वारंटी",
  cat_open: "ओपन टेरेस", cat_open_s: "खुली जगह के लिए पुली सिस्टम",
  cat_ceil: "सीलिंग माउंट", cat_ceil_s: "जगह बचाने वाले सीलिंग सिस्टम",
  cat_wall: "वॉल माउंट", cat_wall_s: "मज़बूत फोल्डेबल वॉल स्टैंड",
  cat_all: "सभी सिस्टम", cat_all_s: "पूरी रेंज देखें",
  pop_eb: "हमारे लोकप्रिय उत्पाद",
  best: "बेस्टसेलर।",
  ed_t: "सिर्फ स्टैंड नहीं, हर घर के लिए स्मार्ट ड्राइंग",
  ed_s: "हम सिर्फ एक दुकान नहीं हैं। हम पुणे के अपने ड्राय-सिस्टम निर्माता हैं, 1,00,000+ घरों को 304-ग्रेड स्टील सिस्टम के साथ उनकी बालकनी वापस दिला रहे हैं।",
  clients_t: "कॉर्पोरेट ग्राहक।",
  view_all: "सभी उत्पाद देखें",
  insp_t: "प्रेरणा पाएं।",
  insp1: "सही ड्राइंग सिस्टम कैसे चुनें?",
  insp2: "अपनी बालकनी खाली कैसे करें?",
  insp3: "ड्राइंग टूल्स जिनके बिना काम नहीं",
  get_insp: "प्रेरणा पाएं",
  moment_l1: "अपना पल",
  moment_l2: "जिएं।",
  rated_t: "रेटिंग 4.8/5।",
  cta_t: "पूरे पुणे में मुफ्त साइट विज़िट।",
  cta_quote: "मुफ्त कोटेशन पाएं",
  cta_cart: "कार्ट देखें",
  foot_tag:
    "पसंद आने वाले कपड़े सुखाने के सिस्टम। पुणे में डिज़ाइन, 304-ग्रेड स्टील में बने, 2014 से 1,00,000+ घरों में इंस्टॉल।",
  foot_shop: "खरीदें",
  foot_service: "सेवा",
  foot_contact: "संपर्क",
  foot_about: "हमारे बारे में",
  shop_title: "ड्राइंग रैक",
  shop_desc:
    "पसंद आने वाले कपड़े सुखाने के स्टैंड। ड्रायर के बिना Excellent Dry पुली सिस्टम पर सुखाएं। मज़बूत, आसान, टेरेस, सीलिंग और दीवार के लिए।",
  filter_t: "फ़िल्टर",
  filter_cat: "श्रेणियां",
  filter_all: "सभी सिस्टम",
  filter_pulley: "पुली ड्राइंग सिस्टम",
  filter_ceiling: "सीलिंग ड्राइंग रैक",
  filter_wall: "वॉल माउंटेड ड्रायर",
  filter_size: "साइज़",
  filter_colour: "रंग",
  products_n: "उत्पाद",
  sort_by: "क्रमबद्ध करें",
  sort_rec: "सुझाए गए",
  sort_low: "कीमत कम",
  sort_high: "कीमत ज़्यादा",
  d_b1: "कॉल/WhatsApp पर मुफ्त माप मार्गदर्शन",
  d_b2: "पूरे पुणे में प्रोफेशनल इंस्टॉलेशन (60-90 मिनट)",
  d_b3: "GST बिल और कॉल पर सर्विस सपोर्ट",
  d_order: "यह उत्पाद ऑर्डर करें।",
  d_ordernow: "अभी ऑर्डर करें",
  d_add: "कार्ट में डालें",
  d_added: "कार्ट में जोड़ा गया",
  card_add: "कार्ट में डालें",
  card_added: "जोड़ा गया",
  cart_title: "आपका कार्ट।",
  cart_empty_t: "कार्ट खाली है।",
  cart_empty_s: "शुरू करने के लिए ड्राइंग सिस्टम जोड़ें।",
  cart_browse: "उत्पाद देखें",
  cart_checkout_t: "चेकआउट।",
  cart_checkout_s: "मुफ्त कॉलबैक के लिए यह कार्ट भेजें, या WhatsApp पर तुरंत ऑर्डर करें।",
  cart_subtotal: "कुल",
  cart_save: "आपकी बचत",
  cart_wa: "WhatsApp पर तुरंत ऑर्डर करें",
  form_name: "आपका नाम *",
  form_phone: "फोन / WhatsApp *",
  form_area: "पुणे में क्षेत्र (जैसे बानेर)",
  form_product: "इच्छुक उत्पाद",
  form_msg: "संदेश (साइज़, मंज़िल, बालकनी...)",
  form_submit: "मुफ्त कॉलबैक पाएं",
  form_sending: "भेजा जा रहा है...",
  form_orcall: "या कॉल करें",
  form_thanks: "धन्यवाद",
  form_back: "हम कुछ कामकाजी घंटों में आपको कॉल करेंगे।",
  form_wa: "WhatsApp पर तुरंत कन्फर्म करें",
  contact_t: "संपर्क।",
  contact_call: "हमें कॉल करें",
  contact_visit: "पता",
  contact_cb: "कॉलबैक का अनुरोध।",
  about_t: "पुणे का अपना ड्राइंग-सिस्टम निर्माता।",
  gallery_t: "प्रेरणा पाएं।",
  gallery_s: "पूरे पुणे में असली इंस्टॉलेशन। नई तस्वीरें Admin Media से जुड़ती हैं।",
  testi_t: "रेटिंग 4.8/5।",
  ret_t: "रिटेलर बनें।",
  delivery_t: "डिलीवरी क्षेत्र",
  select_size: "साइज़ और लाइन चुनें:",
  nav_clients: "ग्राहक",
  cli_t: "हमारे मूल्यवान ग्राहक।",
  cli_res: "रिहायशी ग्राहक",
  cli_govt: "सरकारी ग्राहक",
  cli_hostels: "हॉस्टल",
};

const mr: Record<Key, string> = {
  home: "होम",
  nav_pulley: "पुली सिस्टीम",
  nav_wall: "वॉल माउंट आणि स्टँड",
  nav_gallery: "गॅलरी",
  nav_reviews: "अभिप्राय",
  nav_retailer: "रिटेलर व्हा",
  nav_contact: "संपर्क",
  nav_open: "ओपन टेरेस सिस्टीम",
  nav_ceiling: "सीलिंग माउंट सिस्टीम",
  nav_all: "सर्व्ह ड्रायिंग सिस्टीम",
  nav_fold: "फोल्डेबल वॉल स्टँड",
  search_ph: "उत्पादन शोधा...",
  account: "खाते",
  cart: "कार्ट",
  call_now: "आत्ताच कॉल करा",
  hero_eb: "भारताचा विश्वासार्ह ड्रायिंग सोल्यूशन",
  hero_l1: "स्मार्ट वाळवा.",
  hero_l2: "जागा वाचवा.",
  hero_sub:
    "पुली वाली टेरेस आणि सीलिंग सिस्टीम आणि फोल्डेबल वॉल स्टँड: 304-ग्रेड स्टील, पुण्यात काही दिवसांत इंस्टॉलेशन। 1,00,000+ आनंदी घरे।",
  hero_cta: "कलेक्शन पहा",
  b1t: "304-ग्रेड", b1s: "स्टेनलेस स्टील",
  b2t: "जागा वाचवणारी", b2s: "डिझाइन",
  b3t: "मोफत इंस्टॉलेशन", b3s: "पुण्यात",
  b4t: "1 वर्ष", b4s: "वॉरंटी",
  cat_open: "ओपन टेरेस", cat_open_s: "मोकळ्या जागेसाठी पुली सिस्टीम",
  cat_ceil: "सीलिंग माउंट", cat_ceil_s: "जागा वाचवणारी सीलिंग सिस्टीम",
  cat_wall: "वॉल माउंट", cat_wall_s: "भक्कम फोल्डेबल वॉल स्टँड",
  cat_all: "सर्व्ह सिस्टीम", cat_all_s: "संपूर्ण रेंज पहा",
  pop_eb: "आमची लोकप्रिय उत्पादने",
  best: "बेस्टसेलर।",
  ed_t: "फक्त स्टँड नाही, प्रत्येक घरासाठी स्मार्ट ड्रायिंग",
  ed_s: "आम्ही फक्त एक दुकान नाही। आम्ही पुण्याचे स्वतःचे ड्राय-सिस्टीम निर्माते आहोत, 304-ग्रेड स्टील सिस्टीमसह 1,00,000+ घरांना त्यांची बाल्कनी परत मिळवून देत आहोत।",
  clients_t: "कॉर्पोरेट ग्राहक।",
  view_all: "सर्व्ह उत्पादने पहा",
  insp_t: "प्रेरणा घ्या।",
  insp1: "योग्य ड्रायिंग सिस्टीम कशी निवडावी?",
  insp2: "तुमची बाल्कनी मोकळी कशी करावी?",
  insp3: "ज्यांच्याशिवाय चालणार नाही अशी ड्रायिंग साधने",
  get_insp: "प्रेरणा घ्या",
  moment_l1: "तुमचा क्षण",
  moment_l2: "जगा।",
  rated_t: "रेटिंग 4.8/5।",
  cta_t: "संपूर्ण पुण्यात मोफत साइट व्हिजिट।",
  cta_quote: "मोफत कोटेशन घ्या",
  cta_cart: "कार्ट पहा",
  foot_tag:
    "आवडतील अशी कपडे वाळवण्याची सिस्टीम। पुण्यात डिझाइन, 304-ग्रेड स्टीलमध्ये बनवलेली, 2014 पासून 1,00,000+ घरांमध्ये इंस्टॉल।",
  foot_shop: "खरेदी",
  foot_service: "सेवा",
  foot_contact: "संपर्क",
  foot_about: "आमच्याबद्दल",
  shop_title: "ड्रायिंग रॅक",
  shop_desc:
    "आवडतील असे कपडे वाळवण्याचे स्टँड। ड्रायरशिवाय Excellent Dry पुली सिस्टीमवर वाळवा। भक्कम, सोपी, टेरेस, सीलिंग आणि भिंतीसाठी।",
  filter_t: "फिल्टर",
  filter_cat: "प्रकार",
  filter_all: "सर्व्ह सिस्टीम",
  filter_pulley: "पुली ड्रायिंग सिस्टीम",
  filter_ceiling: "सीलिंग ड्रायिंग रॅक",
  filter_wall: "वॉल माउंटेड ड्रायर",
  filter_size: "आकार",
  filter_colour: "रंग",
  products_n: "उत्पादने",
  sort_by: "क्रमवारी",
  sort_rec: "शिफारस केलेले",
  sort_low: "किंमत कमी",
  sort_high: "किंमत जास्त",
  d_b1: "कॉल/WhatsApp वर मोफत माप मार्गदर्शन",
  d_b2: "संपूर्ण पुण्यात प्रोफेशनल इंस्टॉलेशन (60-90 मिनिटे)",
  d_b3: "GST बिल आणि कॉलवर सर्व्हिस सपोर्ट",
  d_order: "हे उत्पादन ऑर्डर करा।",
  d_ordernow: "आत्ताच ऑर्डर करा",
  d_add: "कार्टमध्ये टाका",
  d_added: "कार्टमध्ये टाकले",
  card_add: "कार्टमध्ये टाका",
  card_added: "टाकले",
  cart_title: "तुमचा कार्ट।",
  cart_empty_t: "कार्ट रिकामा आहे।",
  cart_empty_s: "सुरुवात करण्यासाठी ड्रायिंग सिस्टीम जोडा।",
  cart_browse: "उत्पादने पहा",
  cart_checkout_t: "चेकआउट।",
  cart_checkout_s: "मोफत कॉलबॅकसाठी हा कार्ट पाठवा, किंवा WhatsApp वर लगेच ऑर्डर करा।",
  cart_subtotal: "एकूण",
  cart_save: "तुमची बचत",
  cart_wa: "WhatsApp वर लगेच ऑर्डर करा",
  form_name: "तुमचे नाव *",
  form_phone: "फोन / WhatsApp *",
  form_area: "पुण्यातील क्षेत्र (उदा. बानेर)",
  form_product: "आवडीचे उत्पादन",
  form_msg: "संदेश (आकार, मजला, बाल्कनी...)",
  form_submit: "मोफत कॉलबॅक घ्या",
  form_sending: "पाठवत आहे...",
  form_orcall: "किंवा कॉल करा",
  form_thanks: "धन्यवाद",
  form_back: "आम्ही काही कामकाजी तासांत तुम्हाला कॉल करू।",
  form_wa: "WhatsApp वर लगेच कन्फर्म करा",
  contact_t: "संपर्क।",
  contact_call: "आम्हाला कॉल करा",
  contact_visit: "पत्ता",
  contact_cb: "कॉलबॅक विनंती।",
  about_t: "पुण्याचा स्वतःचा ड्रायिंग-सिस्टीम निर्माता।",
  gallery_t: "प्रेरणा घ्या।",
  gallery_s: "संपूर्ण पुण्यात खरे इंस्टॉलेशन। नवीन फोटो Admin Media मधून जोडले जातात।",
  testi_t: "रेटिंग 4.8/5।",
  ret_t: "रिटेलर व्हा।",
  delivery_t: "डिलिव्हरी क्षेत्र",
  select_size: "आकार आणि लाइन्स निवडा:",
  nav_clients: "ग्राहक",
  cli_t: "आमचे मौल्यवान ग्राहक।",
  cli_res: "निवासी ग्राहक",
  cli_govt: "सरकारी ग्राहक",
  cli_hostels: "वसतिगृहे",
};

const STRINGS = { en, hi, mr };

export function tr(lang: Lang, key: Key): string {
  return STRINGS[lang][key] ?? en[key];
}
